"use client";

import { useState, useEffect, useRef, useId } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Circle, CheckCircle2, UploadCloud, Camera, FileText, X, Printer, RotateCcw, Folder, Edit3, Check, Trash2, Plus, ChevronUp } from "lucide-react";

// ─── Types ───────────────────────────────────────────────────────────────────

type Lang = "zh" | "en";

interface Step {
  id: number;
  text: string;
  original?: string;
  checked: boolean;
  isHeader?: boolean;
  count?: number;
  subCount?: number;
}

interface Project {
  id: string;
  name: string;
  steps: Step[];
  rowCount: number;
  lastUpdated: number;
}

// ─── Translations dictionary ──────────────────────────────────────────────────

const dict = {
  zh: {
    subtitle:       "将你的编织图解转为进度清单",
    tabText:        "文字录入",
    tabAI:          "智能识别",
    placeholder:    "粘贴你的织法图解...\n\n例如：\nR1: knit all. R2: purl all. Repeat R1-R2 for 10 rows.",
    convertBtn:     "开始转换 ✨",
    loadingBtn:     "✨ AI 正在编织清单...",
    errorQuota:     "AI 正在休息（频率限制），请 30 秒后再试。",
    errorTimeout:   "请求超时，请稍后重试。",
    errorKey:       "API Key 无效，请检查 .env.local 文件。",
    errorModel:     "模型暂不可用，请稍后重试。",
    errorUnknown:   "解析失败，请稍后重试。",
    errorFileTooLarge: "图片过大（请控制在 5MB 以内），请压缩后再试。",
    compressing:    "正在压缩图片...",
    uploadTitle:    "拖拽图片或 PDF 到这里",
    uploadSub:      "KnitStep 帮你识别编织步骤",
    uploadClick:    "选择图片 / PDF 或拍照",
    uploadCamera:   "支持直接拍照，也可上传 PDF 文件",
    uploadPdfReady: "PDF 已就绪",
    uploadComing:   "🔜 AI 识别功能即将上线，敬请期待",
    checklistTitle: "步骤清单",
    noMatch:        "未识别到编织行指令。",
    noMatchSub:     "请确认文本包含 Row、R1、knit、purl 等关键词。",
    allDone:        "🎉 全部完成！你的编织作品完工啦！",
    editTip:        "提示：点击任意步骤文字可编辑",
    printBtn:       "打印图解",
    printFooter:    "由 KnitStep 生成",
    resetBtn:       "重置进度",
    resetConfirm:   "确定要清除所有进度吗？",
    myProjects:     "我的项目库",
    saveToLibrary:  "存入项目库",
    noProjects:     "暂无保存的项目",
    projectNamePrompt: "请为项目命名:",
    deleteConfirm:  "确定要删除这个项目吗？",
    editMode:       "编辑",
    editModeDone:   "完成",
    trySample:      "试试示例图解",
    feedback:       "有建议或报错？请告诉我！",
  },
  en: {
    subtitle:       "Turn your knitting patterns into a checklist",
    tabText:        "Text Input",
    tabAI:          "Smart Scan",
    placeholder:    "Paste your pattern here...\n\ne.g.:\nR1: CO 20 sts\nRow 2: Knit all stitches\nR3: K2, P2, repeat to end\nRow 4: Purl all sts\nBind off all sts",
    convertBtn:     "Convert Now ✨",
    loadingBtn:     "✨ AI is weaving your checklist...",
    errorQuota:     "AI is resting (rate limit). Please try again in 30 seconds.",
    errorTimeout:   "Request timed out. Please try again.",
    errorKey:       "Invalid API key. Please check your .env.local file.",
    errorModel:     "Model unavailable. Please try again later.",
    errorUnknown:   "Parsing failed. Please try again.",
    errorFileTooLarge: "Image too large (max 5 MB). Please compress it and try again.",
    compressing:    "Compressing image...",
    uploadTitle:    "Drag an image or PDF here",
    uploadSub:      "KnitStep will recognize your knitting steps",
    uploadClick:    "Browse Files or Take Photo",
    uploadCamera:   "Supports images, PDFs, and camera",
    uploadPdfReady: "PDF ready",
    uploadComing:   "🔜 AI recognition coming soon, stay tuned!",
    checklistTitle: "Checklist",
    noMatch:        "No knitting row instructions detected.",
    noMatchSub:     "Make sure the text contains keywords like Row, R1, knit, purl, etc.",
    allDone:        "🎉 All done! Your knitted piece is complete!",
    editTip:        "Tip: Tap any step text to edit.",
    printBtn:       "Print Pattern",
    printFooter:    "Generated by KnitStep",
    resetBtn:       "Reset Progress",
    resetConfirm:   "Reset all progress?",
    myProjects:     "My Projects",
    saveToLibrary:  "Save",
    noProjects:     "No projects saved yet",
    projectNamePrompt: "Name this project:",
    deleteConfirm:  "Delete this project?",
    editMode:       "Edit",
    editModeDone:   "Done",
    trySample:      "Try Sample Pattern",
    feedback:       "Feedback or bugs? Tell us",
  },
} as const;

// ─── Sample pattern ──────────────────────────────────────────────────────────

const SAMPLE_PATTERN = `PATTERN
BRIM
Cast 60 (68, 76, 84, 92) stitches onto circular needles. We used a basic Long Tail Cast On.

Place unique marker and join for working in the round, being careful not to twist the stitches.

Round 1: *P2, k2, repeat from * to end of round.

Repeat Round 1 until piece measures 3½ (4, 4½, 5, 5) inches from cast-on edge.

BODY
Knit every round until piece measures 8 (8, 8¾, 9¼, 10) inches from cast-on edge.

CROWN
NOTE: If using short circular needles, change to double pointed needles when necessary.

Set-Up Round: Remove unique marker, k3, place unique marker for new end of round, [k15 (17, 19, 21, 23), place marker] 3 times, knit to end of round. [4 total stitch markers, including unique end-of-round marker]

Decrease Round: [Slip slip knit, knit to 2 stitches before next marker, knit 2 together, slip marker] 4 times. [8 stitches decreased]

Next Round: Knit to end of round.

Repeat last two rounds 5 (6, 7, 8, 9) more times. [12 stitches remain]

Cut yarn and thread tail onto a tapestry needle. Sew tail through remaining stitches. Pull taut and bring tail to inside of hat to weave in.

FINISHING
Weave in ends and block as desired.`;

// ─── Parse logic ─────────────────────────────────────────────────────────────

const ROW_KEYWORDS =
  /\b(r\d+|row\s*\d+|repeat|stitch(?:es)?|cast\s*on|cast\s*off|bind\s*off|yarn|knit|purl|k\d+|p\d+|co\b|bo\b|sl\b|yo\b|k2tog|ssk)\b/i;

function parseInput(raw: string): Step[] {
  return raw
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line, idx) => ({ id: idx, text: line, checked: false }))
    .filter((step) => ROW_KEYWORDS.test(step.text));
}

// ─── Image compression ───────────────────────────────────────────────────────

const MAX_DIMENSION = 1280;
const JPEG_QUALITY  = 0.7;

async function compressImage(
  file: File,
): Promise<{ base64: string; mimeType: string; previewUrl: string }> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    const objectUrl = URL.createObjectURL(file);

    img.onload = () => {
      URL.revokeObjectURL(objectUrl);
      let { width, height } = img;

      if (width > MAX_DIMENSION || height > MAX_DIMENSION) {
        if (width >= height) {
          height = Math.round(height * (MAX_DIMENSION / width));
          width  = MAX_DIMENSION;
        } else {
          width  = Math.round(width * (MAX_DIMENSION / height));
          height = MAX_DIMENSION;
        }
      }

      const canvas = document.createElement("canvas");
      canvas.width  = width;
      canvas.height = height;
      const ctx = canvas.getContext("2d");
      if (!ctx) { reject(new Error("Canvas unavailable")); return; }

      ctx.drawImage(img, 0, 0, width, height);
      canvas.toBlob((blob) => {
        if (!blob) { reject(new Error("Compression failed")); return; }
        const reader = new FileReader();
        reader.onload = (e) => {
          const dataUrl = e.target?.result as string;
          const base64  = dataUrl.split(",")[1];
          resolve({ base64, mimeType: "image/jpeg", previewUrl: dataUrl });
        };
        reader.onerror = reject;
        reader.readAsDataURL(blob);
      }, "image/jpeg", JPEG_QUALITY);
    };

    img.onerror = () => { URL.revokeObjectURL(objectUrl); reject(new Error("Image load failed")); };
    img.src = objectUrl;
  });
}

// ─── Shared style tokens ─────────────────────────────────────────────────────

const CARD_STYLE: React.CSSProperties = {
  background: "var(--bg-card)",
  border: "1.5px solid var(--border)",
  boxShadow: "0 10px 40px -15px rgba(0,0,0,0.05)",
};

const RADIUS = "2rem";

// ─── Page ────────────────────────────────────────────────────────────────────

export default function Home() {
  // ── State ──
  const [lang, setLang]                 = useState<Lang>("zh");
  const [inputText, setInputText]       = useState<string>("");
  const [steps, setSteps]               = useState<Step[]>([]);
  const [hasConverted, setHasConverted] = useState(false);
  const [activeTab, setActiveTab]       = useState<"text" | "ai">("text");
  const [isLoading, setIsLoading]       = useState(false);
  const [errorMsg, setErrorMsg]         = useState<string | null>(null);
  const [uploadedImage, setUploadedImage] = useState<{
    base64: string; mimeType: string; previewUrl: string;
  } | null>(null);
  const [isCompressing, setIsCompressing] = useState(false);
  const [tipVisible, setTipVisible]       = useState(true);
  const [mounted, setMounted]             = useState(false);
  const [projects, setProjects]                     = useState<Project[]>([]);
  const [currentProjectId, setCurrentProjectId]     = useState<string | null>(null);
  const [showProjectsModal, setShowProjectsModal]   = useState(false);
  const [isEditMode, setIsEditMode]                 = useState(false);
  const [showBackToTop, setShowBackToTop]           = useState(false);

  useEffect(() => {
    const onScroll = () => setShowBackToTop(window.scrollY > 320);
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);
  const [rateLimitSecondsLeft, setRateLimitSecondsLeft] = useState<number | null>(null);

  // Countdown timer for rate-limit (429)
  useEffect(() => {
    if (!rateLimitSecondsLeft) return;
    const timer = setTimeout(
      () => setRateLimitSecondsLeft((s) => (s !== null && s > 0 ? s - 1 : null)),
      1000,
    );
    return () => clearTimeout(timer);
  }, [rateLimitSecondsLeft]);

  // Guards against saving before hydration completes (avoids overwriting restored data)
  const hydrated = useRef(false);

  // ── Hydration — restore all state from localStorage on first mount ──
  useEffect(() => {
    if (typeof window === "undefined") return;

    const savedLang = localStorage.getItem("knitstep-lang");
    const savedData = localStorage.getItem("knitstep-data");

    const restoredLang: Lang =
      savedLang === "zh" || savedLang === "en" ? savedLang : "zh";
    setLang(restoredLang);

    if (savedData) {
      try {
        const { inputText: si, steps: ss, hasConverted: sc } = JSON.parse(savedData);
        if (typeof si === "string") setInputText(si);
        if (Array.isArray(ss))     setSteps(ss);
        if (typeof sc === "boolean") setHasConverted(sc);
      } catch {
        // Corrupt data — start fresh
      }
    }

    if (localStorage.getItem("knitstep-tip-dismissed") === "1") setTipVisible(false);

    let restoredProjects: Project[] = [];
    const savedProjects = localStorage.getItem("knitstep-projects");
    if (savedProjects) {
      try {
        const parsed = JSON.parse(savedProjects);
        if (Array.isArray(parsed)) {
          restoredProjects = parsed;
          setProjects(parsed);
        }
      } catch { /* ignore corrupt data */ }
    }

    // Restore the active project so the sync effect keeps saving without requiring
    // the user to re-open the project library after a page refresh.
    const savedProjectId = localStorage.getItem("knitstep-current-project");
    if (savedProjectId && restoredProjects.some((p) => p.id === savedProjectId)) {
      setCurrentProjectId(savedProjectId);
    }

    hydrated.current = true;
    setMounted(true);
  }, []);

  // ── Persistence — save whenever relevant state changes ──
  useEffect(() => {
    if (!hydrated.current) return;
    if (typeof window === "undefined") return;
    localStorage.setItem(
      "knitstep-data",
      JSON.stringify({ inputText, steps, hasConverted })
    );
  }, [inputText, steps, hasConverted]);

  // ── Persist active project ID so the sync effect survives page refreshes ──
  useEffect(() => {
    if (!hydrated.current) return;
    if (currentProjectId) {
      localStorage.setItem("knitstep-current-project", currentProjectId);
    } else {
      localStorage.removeItem("knitstep-current-project");
    }
  }, [currentProjectId]);

  // ── Project sync — update active project whenever steps change ──
  useEffect(() => {
    if (!hydrated.current) return;
    if (!currentProjectId) return;
    setProjects((prev) => {
      const updated = prev.map((p) =>
        p.id === currentProjectId
          ? { ...p, steps, rowCount: steps.filter((s) => !s.isHeader).length, lastUpdated: Date.now() }
          : p
      );
      localStorage.setItem("knitstep-projects", JSON.stringify(updated));
      return updated;
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [steps, currentProjectId]);

  function toggleLang() {
    const next: Lang = lang === "zh" ? "en" : "zh";
    setLang(next);
    localStorage.setItem("knitstep-lang", next);
  }

  const t = dict[lang];

  async function handleFileUpload(file: File) {
    const MAX_IMAGE_BYTES = 5 * 1024 * 1024;  // 5 MB for images
    const MAX_FILE_BYTES  = 10 * 1024 * 1024; // 10 MB for PDFs
    const limit = file.type.startsWith("image/") ? MAX_IMAGE_BYTES : MAX_FILE_BYTES;
    if (file.size > limit) {
      setErrorMsg(t.errorFileTooLarge);
      return;
    }
    setErrorMsg(null);

    if (file.type.startsWith("image/")) {
      setIsCompressing(true);
      try {
        const compressed = await compressImage(file);
        setUploadedImage(compressed);
      } catch {
        // Fall back to raw file if compression errors
        const reader = new FileReader();
        reader.onload = (e) => {
          const dataUrl = e.target?.result as string;
          const [header, base64] = dataUrl.split(",");
          const mimeType = header.split(":")[1].split(";")[0];
          setUploadedImage({ base64, mimeType, previewUrl: dataUrl });
        };
        reader.readAsDataURL(file);
      } finally {
        setIsCompressing(false);
      }
    } else {
      // PDF or other non-image — pass through as-is (Canvas cannot compress PDFs)
      const reader = new FileReader();
      reader.onload = (e) => {
        const dataUrl = e.target?.result as string;
        const [header, base64] = dataUrl.split(",");
        const mimeType = header.split(":")[1].split(";")[0];
        setUploadedImage({ base64, mimeType, previewUrl: dataUrl });
      };
      reader.readAsDataURL(file);
    }
  }

  async function handleConvert() {
    setIsLoading(true);
    setErrorMsg(null);
    setRateLimitSecondsLeft(null);

    // ⚠️ 关键修复：在开始转换前，彻底清空旧的步骤和状态
    // 先清除 currentProjectId，防止 sync effect 把旧项目覆盖为空步骤
    setIsEditMode(false);
    setCurrentProjectId(null);
    setSteps([]);
    setHasConverted(false);

    try {
      const body = activeTab === "ai" && uploadedImage
        ? { text: "", language: lang, imageBase64: uploadedImage.base64, imageMimeType: uploadedImage.mimeType }
        : { text: inputText, language: lang };
      const res = await fetch("/api/parse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "UNKNOWN_ERROR");
      const rawSteps: { text: string; original?: string }[] = data.steps;
      const parsed: Step[] = rawSteps.map((s, idx) => ({
        id:       Date.now() + idx,
        text:     s.text,
        original: s.original,
        checked:  false,
      }));
      setSteps(parsed);
      setHasConverted(true);

      // Auto-save as a new project (only when there are actual steps)
      if (parsed.filter((s) => !s.isHeader).length > 0) {
        const now = Date.now();
        const d   = new Date(now);
        const projectName =
          lang === "zh"
            ? `${d.getMonth() + 1}月${d.getDate()}日 项目`
            : `${d.toLocaleDateString("en-US", { month: "short", day: "numeric" })} Project`;
        const newProject: Project = {
          id:          now.toString(),
          name:        projectName,
          steps:       parsed,
          rowCount:    parsed.filter((s) => !s.isHeader).length,
          lastUpdated: now,
        };
        setProjects((prev) => {
          const updated = [newProject, ...prev];
          localStorage.setItem("knitstep-projects", JSON.stringify(updated));
          return updated;
        });
        setCurrentProjectId(now.toString());
      }
    } catch (err: any) {
      const msg = err?.message ?? "";
      if      (msg === "QUOTA_EXCEEDED")    { setRateLimitSecondsLeft(30); }
      else if (msg === "FILE_TOO_LARGE")    setErrorMsg(t.errorFileTooLarge);
      else if (msg === "API_KEY_MISSING")   setErrorMsg(t.errorKey);
      else if (msg === "MODEL_UNAVAILABLE") setErrorMsg(t.errorModel);
      else                                  setErrorMsg(t.errorUnknown);
    } finally {
      setIsLoading(false);
    }
  }

  // 清除功能：重置所有状态并清空缓存
  function handleClear() {
    if (confirm(lang === "zh" ? "确定要清除所有进度并重新开始吗？" : "Clear all progress and restart?")) {
      setIsEditMode(false);
      setCurrentProjectId(null);
      setSteps([]);
      setHasConverted(false);
      setInputText("");
      localStorage.removeItem("knitstep-data");
      // 强制页面稍微滚动到顶部
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  }

  function toggleStep(id: number) {
    setSteps((prev) =>
      prev.map((s) => {
        if (s.id !== id) return s;
        return { ...s, checked: !s.checked };
      })
    );
  }

  function updateSubCount(id: number, delta: number) {
    setSteps((prev) =>
      prev.map((s) => {
        if (s.id !== id) return s;
        const max = parseMaxCount(s);
        const raw = (s.subCount ?? 0) + delta;
        const capped = max !== null ? Math.min(max, Math.max(0, raw)) : Math.max(0, raw);
        return {
          ...s,
          subCount: capped,
          checked: max !== null && capped >= max ? true : s.checked,
        };
      })
    );
  }

  function dismissTip() {
    setTipVisible(false);
    localStorage.setItem("knitstep-tip-dismissed", "1");
  }

  function handleTextEdit(id: number, newText: string) {
    setSteps((prev) => prev.map((s) => s.id === id ? { ...s, text: newText } : s));
  }

  function handleReset() {
    if (!confirm(t.resetConfirm)) return;
    setSteps((prev) => prev.map((s) => ({ ...s, checked: false, subCount: 0 })));
  }

  function addStep(insertAt: number) {
    setSteps((prev) => {
      const newStep: Step = { id: Date.now(), text: lang === "zh" ? "新步骤" : "New step", checked: false };
      const next = [...prev];
      next.splice(insertAt, 0, newStep);
      return next;
    });
  }

  function deleteStep(id: number) {
    setSteps((prev) => prev.filter((s) => s.id !== id));
  }


  function handleLoadProject(id: string) {
    const project = projects.find((p) => p.id === id);
    if (!project) return;
    setSteps(project.steps);
    setHasConverted(true);
    setCurrentProjectId(id);
    setShowProjectsModal(false);
  }

  function handleDeleteProject(id: string) {
    if (!confirm(t.deleteConfirm)) return;
    setProjects((prev) => {
      const updated = prev.filter((p) => p.id !== id);
      localStorage.setItem("knitstep-projects", JSON.stringify(updated));
      return updated;
    });
    if (currentProjectId === id) setCurrentProjectId(null);
  }

  function handleRenameProject(id: string, name: string) {
    setProjects((prev) => {
      const updated = prev.map((p) => p.id === id ? { ...p, name } : p);
      localStorage.setItem("knitstep-projects", JSON.stringify(updated));
      return updated;
    });
  }

  function handlePrint() {
    const currentProject = currentProjectId
      ? projects.find((p) => p.id === currentProjectId)
      : null;
    const printTitle = currentProject?.name ?? (lang === "zh" ? "KnitStep · 织步" : "KnitStep");

    function esc(s: string) {
      return s
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;");
    }

    const stepsHtml = steps.map((step) => {
      if (step.isHeader) {
        return `<div class="hdr">${esc(step.text)}</div>`;
      }
      return `<div class="step${step.checked ? " done" : ""}">
        <span class="chk">${step.checked ? "✓" : "○"}</span>
        <div>
          <div class="txt">${esc(step.text)}</div>
          ${step.original ? `<div class="orig">${esc(step.original)}</div>` : ""}
        </div>
      </div>`;
    }).join("");

    const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>KnitStep</title>
<style>
  @page { size: A4; margin: 20mm 15mm; }
  body { font-family: system-ui, -apple-system, sans-serif; color: #111; max-width: 640px; margin: 0 auto; padding: 20px; }
  h1 { text-align: center; font-size: 18pt; margin: 0 0 4pt; }
  .sub { text-align: center; font-size: 9pt; color: #888; margin: 0 0 16pt; }
  .hdr { background: #8faf96; color: #fff; font-weight: 700; border-radius: 6px; padding: 6px 12px; margin-bottom: 5px; font-size: 10pt; }
  .step { display: flex; align-items: flex-start; gap: 10px; border: 1px solid #d1d5db; border-radius: 6px; padding: 7px 12px; margin-bottom: 5px; page-break-inside: avoid; }
  .done { background: #f9fafb; border-color: #e5e7eb; }
  .chk { flex-shrink: 0; font-size: 13px; margin-top: 3px; color: #555; }
  .txt { font-size: 10.5pt; line-height: 1.45; }
  .done .txt { color: #6b7280; text-decoration: line-through; }
  .orig { font-size: 8pt; color: #9ca3af; margin-top: 2px; }
  .footer { display: flex; justify-content: space-between; margin-top: 20pt; padding-top: 6pt; border-top: 1px solid #d1d5db; font-size: 8pt; color: #9ca3af; }
</style>
</head>
<body>
  <h1>${esc(printTitle)}</h1>
  <p class="sub">${esc(t.checklistTitle)}</p>
  ${stepsHtml}
  <div class="footer">
    <span>${esc(t.printFooter)}</span>
  </div>
  <script>window.addEventListener('load', function() { window.print(); });<\/script>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (!win) {
      // Popup blocked (common on mobile) — navigate current window instead.
      // The HTML auto-triggers print on load; Back returns to the app.
      window.location.href = url;
    }
  }

  const checkableSteps = steps.filter((s) => !s.isHeader);
  const doneCount      = checkableSteps.filter((s) => s.checked).length;
  const totalCount     = checkableSteps.length;
  const allDone        = totalCount > 0 && doneCount === totalCount;
  const isDisabled = (activeTab === "text" ? inputText.trim().length === 0 : !uploadedImage) || isLoading || isCompressing;

  return (
    <div
      className="print-container relative min-h-screen flex flex-col items-center py-16 px-4"
      style={{ background: "var(--bg)", fontFamily: "var(--font-body)" }}
    >
      {/* ── Language toggle — fixed top-right ── */}
      <div className="no-print absolute top-5 right-5 z-10">
        <LangToggle lang={lang} onToggle={toggleLang} />
      </div>

      {/* ── Header ── */}
      <motion.header
        initial={{ opacity: 0, y: -24 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="print-header mb-8 relative w-full max-w-xl flex flex-col items-center gap-3 text-center px-16"
      >
        <div className="no-print absolute left-4 sm:left-6 top-1 transition-transform">
          <KnitLogo />
        </div>

        {/* My Projects — symmetric with logo, right side */}
        <motion.button
          onClick={() => setShowProjectsModal(true)}
          whileHover={{ scale: 1.05 }}
          whileTap={{ scale: 0.95 }}
          transition={{ type: "spring", stiffness: 400, damping: 20 }}
          className="no-print absolute right-2 sm:right-6 top-0 flex-shrink-0"
          style={{ background: "none", border: "none", cursor: "pointer", padding: 0, lineHeight: 0 }}
          aria-label={t.myProjects}
        >
          <div style={{
            width: 56, height: 56, position: "relative",
            display: "flex", flexDirection: "column",
            alignItems: "center", justifyContent: "center", gap: "3px",
          }}>
            <Folder size={26} strokeWidth={1.3} style={{ color: "var(--morandi-green)" }} />
            <span style={{
              fontSize: "9px", fontWeight: 700,
              color: "var(--morandi-green)", letterSpacing: "0.04em",
              lineHeight: 1,
            }}>
              {lang === "zh" ? "项目库" : "Projects"}
            </span>
            {projects.length > 0 && (
              <span style={{
                position: "absolute", top: 6, right: 6,
                background: "var(--morandi-pink)", color: "#fff",
                borderRadius: "999px", fontSize: "9px", fontWeight: 700,
                minWidth: "14px", height: "14px", padding: "0 3px",
                display: "flex", alignItems: "center", justifyContent: "center",
                lineHeight: 1,
              }}>
                {projects.length}
              </span>
            )}
          </div>
        </motion.button>
        <div>
          <h1 className="text-3xl font-bold leading-tight flex items-center justify-center gap-2">
            <span style={{
              fontFamily: "var(--font-quicksand), 'Nunito', sans-serif",
              color: "var(--morandi-green)",
              letterSpacing: "0.04em",
            }}>
              KnitStep
            </span>
            <span aria-hidden="true" style={{ color: "var(--morandi-green)", fontWeight: 700, fontSize: "0.6em", lineHeight: 1 }}>●</span>
            <span style={{
              fontFamily: 'var(--font-zcool), "PingFang SC", sans-serif',
              fontWeight: 700,
              letterSpacing: "0.1em",
              color: "var(--morandi-green)",
            }}>
              织步
            </span>
          </h1>
          <AnimatePresence mode="wait">
            <motion.p
              key={lang + "-subtitle"}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.22 }}
              className="no-print mt-1 text-sm font-medium"
              style={{ color: "var(--text-muted)" }}
            >
              {t.subtitle}
            </motion.p>
          </AnimatePresence>
        </div>
      </motion.header>

      {/* ── Input Card ── */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="no-print w-full max-w-xl mb-6"
        style={{ ...CARD_STYLE, borderRadius: RADIUS, overflow: "hidden" }}
      >
        {/* ── Tabs ── */}
        <div className="flex" style={{ borderBottom: "1.5px solid var(--border)" }}>
          {(["text", "ai"] as const).map((tab) => {
            const label  = tab === "text" ? t.tabText : t.tabAI;
            const active = activeTab === tab;
            return (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className="relative flex-1 py-3.5 text-sm font-semibold tracking-wide transition-colors duration-200"
                style={{
                  color:      active ? "var(--morandi-pink)" : "var(--text-muted)",
                  background: "transparent",
                  border:     "none",
                  cursor:     "pointer",
                }}
              >
                <AnimatePresence mode="wait">
                  <motion.span
                    key={lang + tab}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.18 }}
                  >
                    {label}
                  </motion.span>
                </AnimatePresence>

                {active && (
                  <motion.span
                    layoutId="tab-indicator"
                    className="absolute bottom-0 left-0 right-0 h-0.5 rounded-full"
                    style={{ background: "var(--morandi-pink)" }}
                    transition={{ type: "spring", stiffness: 400, damping: 30 }}
                  />
                )}
              </button>
            );
          })}
        </div>

        {/* ── Tab panels ── */}
        <div className="p-8">
          <AnimatePresence mode="wait">

            {/* Text panel */}
            {activeTab === "text" && (
              <motion.div
                key="text"
                initial={{ opacity: 0, x: -14 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 14 }}
                transition={{ duration: 0.2, ease: "easeOut" }}
              >
                <textarea
                  id="pattern-input"
                  rows={7}
                  suppressHydrationWarning
                  maxLength={10000}
                  className="w-full p-4 text-base resize-none focus:outline-none transition-all duration-200"
                  style={{
                    background:  "var(--bg)",
                    border:      "1.5px solid var(--border)",
                    borderRadius: "1.25rem",
                    color:       "var(--text-main)",
                    fontFamily:  "var(--font-body)",
                  }}
                  onFocus={(e) =>
                    (e.currentTarget.style.border = "1.5px solid var(--morandi-pink)")
                  }
                  onBlur={(e) =>
                    (e.currentTarget.style.border = "1.5px solid var(--border)")
                  }
                  placeholder={t.placeholder}
                  value={inputText}
                  onChange={(e) => setInputText(e.target.value)}
                />
                <div className="flex items-center justify-between mt-1.5 px-1">
                  <button
                    type="button"
                    onClick={() => setInputText(SAMPLE_PATTERN)}
                    className="text-xs font-medium underline-offset-2 underline transition-opacity hover:opacity-70"
                    style={{ color: "var(--morandi-sage)", background: "none", border: "none", cursor: "pointer", padding: 0 }}
                  >
                    {t.trySample}
                  </button>
                  {mounted && (
                    <span
                      className="text-xs tabular-nums"
                      style={{ color: inputText.length >= 4800 ? "var(--morandi-blush)" : "var(--text-muted)" }}
                    >
                      {inputText.length} / 10000
                    </span>
                  )}
                </div>

                <motion.button
                  onClick={handleConvert}
                  disabled={isDisabled}
                  whileHover={isDisabled ? {} : { scale: 1.05 }}
                  whileTap={isDisabled ? {} : { scale: 0.95 }}
                  // breathing animation while loading
                  animate={isLoading ? { opacity: [1, 0.55, 1] } : { opacity: 1 }}
                  transition={
                    isLoading
                      ? { opacity: { repeat: Infinity, duration: 1.4, ease: "easeInOut" } }
                      : { type: "spring", stiffness: 380, damping: 16 }
                  }
                  className="mt-5 w-full py-3.5 text-base font-semibold tracking-wide"
                  style={{
                    background:   "var(--morandi-pink)",
                    color:        "#fff",
                    borderRadius: RADIUS,
                    boxShadow:    "0 4px 20px -6px rgba(231,200,197,0.7)",
                    opacity:      inputText.trim().length === 0 ? 0.45 : 1,
                    cursor:       isDisabled ? "not-allowed" : "pointer",
                  }}
                >
                  <AnimatePresence mode="wait">
                    <motion.span
                      key={isLoading ? "loading" : lang + "-btn"}
                      initial={{ opacity: 0, y: 4 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -4 }}
                      transition={{ duration: 0.18 }}
                      className="block"
                    >
                      {isLoading ? t.loadingBtn : t.convertBtn}
                    </motion.span>
                  </AnimatePresence>
                </motion.button>

                {/* 新增的清除按钮 */}
                {hasConverted && !isLoading && (
                  <motion.button
                    onClick={handleClear}
                    className="mt-4 text-xs font-medium underline transition-opacity hover:opacity-70 w-full text-center"
                    style={{ color: "var(--text-muted)" }}
                  >
                    {lang === "zh" ? "清除数据并重来" : "Clear and Restart"}
                  </motion.button>
                )}

                {/* ── Error / rate-limit countdown ── */}
                <AnimatePresence>
                  {rateLimitSecondsLeft !== null && rateLimitSecondsLeft > 0 ? (
                    <motion.p
                      key="countdown"
                      initial={{ opacity: 0, y: -6 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -6 }}
                      transition={{ duration: 0.2 }}
                      className="mt-3 text-center text-xs font-medium"
                      style={{ color: "var(--morandi-stone)" }}
                    >
                      ⏳ {lang === "zh"
                        ? `AI 正在休息，${rateLimitSecondsLeft} 秒后可重试…`
                        : `AI is resting — retry in ${rateLimitSecondsLeft}s…`}
                    </motion.p>
                  ) : rateLimitSecondsLeft === 0 ? (
                    <motion.p
                      key="countdown-done"
                      initial={{ opacity: 0, y: -6 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -6 }}
                      transition={{ duration: 0.2 }}
                      className="mt-3 text-center text-xs font-medium"
                      style={{ color: "var(--morandi-green)" }}
                    >
                      ✅ {lang === "zh" ? "可以重试了！" : "Ready to retry!"}
                    </motion.p>
                  ) : errorMsg ? (
                    <motion.p
                      key="error"
                      initial={{ opacity: 0, y: -6 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -6 }}
                      transition={{ duration: 0.2 }}
                      className="mt-3 text-center text-xs font-medium"
                      style={{ color: "var(--morandi-blush)" }}
                    >
                      ⚠️ {errorMsg}
                    </motion.p>
                  ) : null}
                </AnimatePresence>
              </motion.div>
            )}

            {/* AI Upload panel */}
            {activeTab === "ai" && (
              <motion.div
                key="ai"
                initial={{ opacity: 0, x: 14 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -14 }}
                transition={{ duration: 0.2, ease: "easeOut" }}
              >
                <AnimatePresence mode="wait">
                  {isCompressing ? (
                    /* ── Compressing state ── */
                    <motion.div
                      key="compressing"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      transition={{ duration: 0.2 }}
                      className="flex flex-col items-center justify-center gap-3"
                      style={{ minHeight: "220px" }}
                    >
                      <motion.div
                        animate={{ rotate: 360 }}
                        transition={{ repeat: Infinity, duration: 1.1, ease: "linear" }}
                        style={{
                          width:       "2rem",
                          height:      "2rem",
                          borderRadius: "50%",
                          border:      "2.5px solid var(--morandi-pink)",
                          borderTopColor: "transparent",
                        }}
                      />
                      <p className="text-sm" style={{ color: "var(--text-muted)" }}>
                        {t.compressing}
                      </p>
                    </motion.div>
                  ) : uploadedImage ? (
                    /* ── Preview state ── */
                    <motion.div
                      key="preview"
                      initial={{ opacity: 0, scale: 0.97 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.97 }}
                      transition={{ duration: 0.2 }}
                      className="relative"
                    >
                      {uploadedImage.mimeType === "application/pdf" ? (
                        /* ── PDF preview ── */
                        <div
                          className="w-full flex flex-col items-center justify-center gap-3 rounded-2xl py-10"
                          style={{ border: "1.5px solid var(--border)", background: "var(--bg)" }}
                        >
                          <FileText size={48} strokeWidth={1.3} style={{ color: "var(--morandi-sage)" }} />
                          <p className="text-sm font-medium" style={{ color: "var(--text-main)" }}>
                            {t.uploadPdfReady}
                          </p>
                        </div>
                      ) : (
                        /* ── Image preview ── */
                        <img
                          src={uploadedImage.previewUrl}
                          alt="pattern preview"
                          className="w-full object-contain rounded-2xl"
                          style={{ maxHeight: "220px", border: "1.5px solid var(--border)" }}
                        />
                      )}
                      <button
                        onClick={() => setUploadedImage(null)}
                        className="absolute top-2 right-2 w-7 h-7 flex items-center justify-center rounded-full text-xs font-bold"
                        style={{
                          background: "rgba(0,0,0,0.45)",
                          color: "#fff",
                          border: "none",
                          cursor: "pointer",
                          lineHeight: 0,
                        }}
                      >
                        ✕
                      </button>
                    </motion.div>
                  ) : (
                    /* ── Drop zone ── */
                    <motion.label
                      key="dropzone"
                      htmlFor="file-upload"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      exit={{ opacity: 0 }}
                      transition={{ duration: 0.2 }}
                      className="flex flex-col items-center justify-center gap-4 w-full cursor-pointer transition-all duration-200"
                      style={{
                        minHeight:    "220px",
                        border:       "2px dashed var(--morandi-sage)",
                        borderRadius: "1.5rem",
                        background:   "var(--bg)",
                      }}
                      onDragOver={(e) => {
                        e.preventDefault();
                        e.currentTarget.style.borderColor = "var(--morandi-pink)";
                        e.currentTarget.style.background  = "var(--bg-card)";
                      }}
                      onDragLeave={(e) => {
                        e.currentTarget.style.borderColor = "var(--morandi-sage)";
                        e.currentTarget.style.background  = "var(--bg)";
                      }}
                      onDrop={(e) => {
                        e.preventDefault();
                        e.currentTarget.style.borderColor = "var(--morandi-sage)";
                        e.currentTarget.style.background  = "var(--bg)";
                        const file = e.dataTransfer.files?.[0];
                        if (file) handleFileUpload(file);
                      }}
                    >
                      <motion.div
                        animate={{ y: [0, -5, 0] }}
                        transition={{ repeat: Infinity, duration: 2.6, ease: "easeInOut" }}
                      >
                        <UploadCloud size={48} strokeWidth={1.4} style={{ color: "var(--morandi-sage)" }} />
                      </motion.div>
                      <div className="text-center px-4">
                        <AnimatePresence mode="wait">
                          <motion.div
                            key={lang + "-upload"}
                            initial={{ opacity: 0, y: 6 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -6 }}
                            transition={{ duration: 0.2 }}
                          >
                            <p className="text-sm font-semibold" style={{ color: "var(--text-main)" }}>{t.uploadTitle}</p>
                            <p className="mt-1 text-xs" style={{ color: "var(--text-muted)" }}>{t.uploadSub}</p>
                            {/* Thumb-sized tap target: min 44px height via py-3 */}
                            <span
                              className="mt-4 inline-flex items-center gap-2 text-sm font-semibold px-6 py-3 rounded-full"
                              style={{ background: "var(--morandi-sage)", color: "#fff", minHeight: "44px" }}
                            >
                              <Camera size={16} strokeWidth={2} />
                              <FileText size={15} strokeWidth={2} />
                              {t.uploadClick}
                            </span>
                          </motion.div>
                        </AnimatePresence>
                      </div>
                      <input
                        id="file-upload"
                        type="file"
                        accept="image/*,application/pdf"
                        className="hidden"
                        onChange={(e) => {
                          const file = e.target.files?.[0];
                          if (file) handleFileUpload(file);
                        }}
                      />
                    </motion.label>
                  )}
                </AnimatePresence>

                {/* Convert button — only shown after image is selected */}
                <AnimatePresence>
                  {uploadedImage && (
                    <motion.div
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: 8 }}
                      transition={{ duration: 0.2 }}
                    >
                      <motion.button
                        onClick={handleConvert}
                        disabled={isLoading}
                        whileHover={isLoading ? {} : { scale: 1.05 }}
                        whileTap={isLoading ? {} : { scale: 0.95 }}
                        animate={isLoading ? { opacity: [1, 0.55, 1] } : { opacity: 1 }}
                        transition={
                          isLoading
                            ? { opacity: { repeat: Infinity, duration: 1.4, ease: "easeInOut" } }
                            : { type: "spring", stiffness: 380, damping: 16 }
                        }
                        className="mt-5 w-full py-3.5 text-base font-semibold tracking-wide"
                        style={{
                          background:   "var(--morandi-pink)",
                          color:        "#fff",
                          borderRadius: RADIUS,
                          boxShadow:    "0 4px 20px -6px rgba(231,200,197,0.7)",
                          cursor:       isLoading ? "not-allowed" : "pointer",
                          border:       "none",
                        }}
                      >
                        <AnimatePresence mode="wait">
                          <motion.span
                            key={isLoading ? "loading" : lang + "-img-btn"}
                            initial={{ opacity: 0, y: 4 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -4 }}
                            transition={{ duration: 0.18 }}
                            className="block"
                          >
                            {isLoading ? t.loadingBtn : t.convertBtn}
                          </motion.span>
                        </AnimatePresence>
                      </motion.button>
                    </motion.div>
                  )}
                </AnimatePresence>

                {/* ── Error / rate-limit countdown (AI tab) ── */}
                <AnimatePresence>
                  {rateLimitSecondsLeft !== null && rateLimitSecondsLeft > 0 ? (
                    <motion.p
                      key="countdown-ai"
                      initial={{ opacity: 0, y: -6 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -6 }}
                      transition={{ duration: 0.2 }}
                      className="mt-3 text-center text-xs font-medium"
                      style={{ color: "var(--morandi-stone)" }}
                    >
                      ⏳ {lang === "zh"
                        ? `AI 正在休息，${rateLimitSecondsLeft} 秒后可重试…`
                        : `AI is resting — retry in ${rateLimitSecondsLeft}s…`}
                    </motion.p>
                  ) : rateLimitSecondsLeft === 0 ? (
                    <motion.p
                      key="countdown-ai-done"
                      initial={{ opacity: 0, y: -6 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -6 }}
                      transition={{ duration: 0.2 }}
                      className="mt-3 text-center text-xs font-medium"
                      style={{ color: "var(--morandi-green)" }}
                    >
                      ✅ {lang === "zh" ? "可以重试了！" : "Ready to retry!"}
                    </motion.p>
                  ) : errorMsg ? (
                    <motion.p
                      key="error-ai"
                      initial={{ opacity: 0, y: -6 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -6 }}
                      transition={{ duration: 0.2 }}
                      className="mt-3 text-center text-xs font-medium"
                      style={{ color: "var(--morandi-blush)" }}
                    >
                      ⚠️ {errorMsg}
                    </motion.p>
                  ) : null}
                </AnimatePresence>
              </motion.div>
            )}

          </AnimatePresence>
        </div>
      </motion.div>

      {/* ── Loading skeleton ── */}
      <AnimatePresence>
        {isLoading && <LoadingSkeleton key="skeleton" />}
      </AnimatePresence>

      {/* ── Results Card ── */}
      <AnimatePresence>
        {hasConverted && !isLoading && (
          <motion.div
            key="results"
            initial={{ opacity: 0, y: 28, scale: 0.97 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 16 }}
            transition={{ duration: 0.45, ease: "easeOut" }}
            className="print-results-card w-full max-w-xl p-8"
            style={{ ...CARD_STYLE, borderRadius: RADIUS }}
          >
            {/* ── Header: title row + progress bar, flex-col on mobile ── */}
            <div className="mb-5 flex flex-col gap-3">

              {/* Title + button group — always a single horizontal row */}
              <div className="flex items-center justify-between">
                <AnimatePresence mode="wait">
                  <motion.span
                    key={lang + "-title"}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    transition={{ duration: 0.18 }}
                    className="print-section-title text-sm font-semibold uppercase tracking-widest"
                    style={{ color: "var(--text-muted)" }}
                  >
                    {t.checklistTitle}
                  </motion.span>
                </AnimatePresence>

                {/* Button group + count badge (whole group hidden in print) */}
                <div className="no-print flex items-center gap-2">
                  {/* Print — icon always, label hidden on xs */}
                  <button
                    onClick={handlePrint}
                    className="flex items-center gap-1 text-xs font-medium px-2.5 py-1.5 rounded-full"
                    style={{
                      background: "var(--bg)",
                      color:      "var(--text-muted)",
                      border:     "1px solid var(--border)",
                      cursor:     "pointer",
                    }}
                  >
                    <Printer size={13} strokeWidth={2} />
                    <span className="hidden sm:inline">{t.printBtn}</span>
                  </button>

                  {/* Edit / Done — toggle edit mode */}
                  <button
                    onClick={() => setIsEditMode((v) => !v)}
                    className="flex items-center gap-1 text-xs font-medium px-2.5 py-1.5 rounded-full"
                    style={{
                      background: isEditMode ? "var(--bg-card)" : "var(--bg)",
                      color:      isEditMode ? "var(--morandi-pink)" : "var(--text-muted)",
                      border:     isEditMode ? "1px solid var(--morandi-pink)" : "1px solid var(--border)",
                      cursor:     "pointer",
                    }}
                  >
                    {isEditMode
                      ? <Check size={13} strokeWidth={2.5} />
                      : <Edit3 size={13} strokeWidth={2} />}
                    <span className="hidden sm:inline">
                      {isEditMode ? t.editModeDone : t.editMode}
                    </span>
                  </button>

                  {/* Reset — icon always, label hidden on xs (next to count badge) */}
                  <button
                    onClick={handleReset}
                    className="flex items-center gap-1 text-xs font-medium px-2.5 py-1.5 rounded-full"
                    style={{
                      background: "var(--bg)",
                      color:      "var(--morandi-stone)",
                      border:     "1px solid var(--border)",
                      cursor:     "pointer",
                    }}
                  >
                    <RotateCcw size={13} strokeWidth={2} />
                    <span className="hidden sm:inline">{t.resetBtn}</span>
                  </button>

                  {totalCount > 0 && (
                    <span
                      className="print-count-badge text-sm font-medium px-3 py-1 rounded-full"
                      style={{
                        background: "var(--bg)",
                        color:      "var(--text-muted)",
                        border:     "1px solid var(--border)",
                      }}
                    >
                      {doneCount} / {totalCount}
                    </span>
                  )}
                </div>
              </div>

              {/* Progress bar — full-width on all screens */}
              {totalCount > 0 && (
                <div
                  className="no-print w-full h-2 rounded-full overflow-hidden"
                  style={{ background: "var(--border)" }}
                >
                  <motion.div
                    className="h-full rounded-full"
                    style={{ background: "var(--morandi-green)" }}
                    initial={{ width: 0 }}
                    animate={{ width: `${Math.round((doneCount / totalCount) * 100)}%` }}
                    transition={{ duration: 0.4, ease: "easeOut" }}
                  />
                </div>
              )}
            </div>

            {totalCount === 0 ? (
              <AnimatePresence mode="wait">
                <motion.p
                  key={lang + "-nomatch"}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  exit={{ opacity: 0 }}
                  transition={{ duration: 0.18 }}
                  className="text-sm text-center py-10"
                  style={{ color: "var(--text-muted)" }}
                >
                  {t.noMatch}
                  <br />
                  {t.noMatchSub}
                </motion.p>
              </AnimatePresence>
            ) : (
              <>
                {/* ── Edit tip ── */}
                <AnimatePresence>
                  {tipVisible && (
                    <motion.div
                      key="edit-tip"
                      initial={{ opacity: 0, y: -6 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0, y: -6 }}
                      transition={{ duration: 0.25 }}
                      className="no-print flex items-center justify-between mb-4 px-3 py-2 rounded-xl text-xs font-medium"
                      style={{ background: "#eff6ff", color: "#60a5fa" }}
                    >
                      <span>✏️ {t.editTip}</span>
                      <button
                        onClick={dismissTip}
                        style={{ background: "none", border: "none", cursor: "pointer",
                                 color: "#93c5fd", lineHeight: 0, padding: "2px" }}
                      >
                        <X size={13} strokeWidth={2} />
                      </button>
                    </motion.div>
                  )}
                </AnimatePresence>

                <ul className="flex flex-col gap-2">
                  <AnimatePresence>
                    {isEditMode && (
                      <StepInsertDividerLi key="ins-before-0" onAdd={() => addStep(0)} />
                    )}
                  </AnimatePresence>
                  {steps.flatMap((step, i) => [
                    <StepItem
                      key={step.id}
                      step={step}
                      index={i}
                      isEditMode={isEditMode}
                      onToggle={() => toggleStep(step.id)}
                      onSubCountChange={(delta) => updateSubCount(step.id, delta)}
                      onTextEdit={(text) => handleTextEdit(step.id, text)}
                      onDelete={() => deleteStep(step.id)}
                    />,
                    <AnimatePresence key={`ap-ins-${step.id}`}>
                      {isEditMode && (
                        <StepInsertDividerLi key={`ins-after-${step.id}`} onAdd={() => addStep(i + 1)} />
                      )}
                    </AnimatePresence>,
                  ])}
                </ul>

                <AnimatePresence>
                  {allDone && (
                    <motion.p
                      initial={{ opacity: 0, scale: 0.85 }}
                      animate={{ opacity: 1, scale: 1 }}
                      exit={{ opacity: 0, scale: 0.85 }}
                      transition={{ type: "spring", stiffness: 300, damping: 20 }}
                      className="mt-7 text-center text-sm font-semibold"
                      style={{ color: "var(--morandi-green)" }}
                    >
                      <AnimatePresence mode="wait">
                        <motion.span
                          key={lang + "-done"}
                          initial={{ opacity: 0 }}
                          animate={{ opacity: 1 }}
                          exit={{ opacity: 0 }}
                          transition={{ duration: 0.18 }}
                        >
                          {t.allDone}
                        </motion.span>
                      </AnimatePresence>
                    </motion.p>
                  )}
                </AnimatePresence>

                {/* ── Feedback link ── */}
                <div className="no-print mt-6 flex items-center justify-center gap-2 flex-wrap">
                  <span className="text-xs" style={{ color: "var(--text-muted)" }}>{t.feedback}</span>
                  <a
                    href="https://xhslink.com/m/A11u8iECHmb"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs font-semibold underline underline-offset-2 transition-opacity hover:opacity-70"
                    style={{ color: "var(--morandi-pink)" }}
                  >
                    小红书
                  </a>
                  <span className="text-xs" style={{ color: "var(--text-muted)" }}>·</span>
                  <a
                    href="https://www.instagram.com/gammeeloveknitting/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-xs font-semibold underline underline-offset-2 transition-opacity hover:opacity-70"
                    style={{ color: "var(--morandi-pink)" }}
                  >
                    Instagram
                  </a>
                </div>

                {/* ── Print-only footer ── */}
                <div className="print-footer">
                  <span>{t.printFooter}</span>
                </div>
              </>
            )}
          </motion.div>
        )}
      </AnimatePresence>

      {/* ── Back to top ── */}
      <AnimatePresence>
        {showBackToTop && (
          <motion.button
            key="back-to-top"
            initial={{ opacity: 0, y: 16, scale: 0.85 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 16, scale: 0.85 }}
            transition={{ type: "spring", stiffness: 380, damping: 22 }}
            whileHover={{ scale: 1.12, y: -2 }}
            whileTap={{ scale: 0.92 }}
            onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
            className="no-print fixed bottom-6 right-5 z-40 flex flex-col items-center justify-center gap-0.5"
            aria-label="Back to top"
            style={{
              width:        "46px",
              height:       "46px",
              borderRadius: "999px",
              background:   "var(--morandi-pink)",
              boxShadow:    "0 4px 18px -4px rgba(231,183,180,0.6)",
              border:       "none",
              cursor:       "pointer",
              color:        "#fff",
            }}
          >
            <ChevronUp size={20} strokeWidth={2.5} />
          </motion.button>
        )}
      </AnimatePresence>

      {/* ── Projects Modal ── */}
      <AnimatePresence>
        {showProjectsModal && (
          <ProjectsModal
            projects={projects}
            lang={lang}
            currentProjectId={currentProjectId}
            onClose={() => setShowProjectsModal(false)}
            onLoad={handleLoadProject}
            onDelete={handleDeleteProject}
            onRename={handleRenameProject}
          />
        )}
      </AnimatePresence>
    </div>
  );
}

// ─── LangToggle ──────────────────────────────────────────────────────────────

function LangToggle({ lang, onToggle }: { lang: Lang; onToggle: () => void }) {
  return (
    <motion.button
      onClick={onToggle}
      whileHover={{ scale: 1.06 }}
      whileTap={{ scale: 0.94 }}
      transition={{ type: "spring", stiffness: 400, damping: 20 }}
      className="flex items-center gap-0.5 p-1 text-xs font-bold tracking-wider"
      style={{
        background:   "var(--morandi-stone)",
        borderRadius: "999px",
        border:       "1.5px solid var(--border)",
        boxShadow:    "0 2px 12px -4px rgba(0,0,0,0.1)",
        cursor:       "pointer",
      }}
      aria-label="Toggle language"
    >
      {(["zh", "en"] as const).map((l) => {
        const active = lang === l;
        return (
          <motion.span
            key={l}
            animate={{
              background: active ? "var(--morandi-pink)" : "transparent",
              color:      active ? "#fff" : "var(--text-muted)",
            }}
            transition={{ duration: 0.25, ease: "easeInOut" }}
            className="relative px-2.5 py-1 rounded-full"
            style={{ minWidth: "2rem", textAlign: "center" }}
          >
            {l === "zh" ? "ZH" : "EN"}
          </motion.span>
        );
      })}
    </motion.button>
  );
}

// ─── KnitLogo ────────────────────────────────────────────────────────────────

function KnitLogo({ className = "w-10 h-10 sm:w-12 sm:h-12" }: { className?: string }) {
  const uid = useId();
  const clipId = `kl-${uid.replace(/:/g, "")}`;

  return (
    <svg className={className} viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <clipPath id={clipId}>
          <circle cx="50" cy="50" r="35" />
        </clipPath>
      </defs>

      {/* Needle 1 — steep rightward lean */}
      <line x1="25" y1="8" x2="75" y2="92" stroke="#C4A882" strokeWidth="4.5" strokeLinecap="round" />
      <circle cx="25" cy="8" r="5.5" fill="#C4A882" />
      <circle cx="23" cy="6" r="2" fill="white" fillOpacity="0.4" />

      {/* Needle 2 — shallow rightward lean */}
      <line x1="8" y1="30" x2="92" y2="70" stroke="#C4A882" strokeWidth="4.5" strokeLinecap="round" />
      <circle cx="8" cy="30" r="5.5" fill="#C4A882" />
      <circle cx="6" cy="28" r="2" fill="white" fillOpacity="0.4" />

      {/* Yarn ball — Morandi green */}
      <circle cx="50" cy="50" r="35" fill="#A8BFA0" />

      {/* Yarn winding texture clipped inside ball */}
      <g clipPath={`url(#${clipId})`}>
        <path d="M 72 16 Q 50 50 28 84" stroke="white" strokeOpacity="0.22" strokeWidth="3.5" fill="none" strokeLinecap="round" />
        <path d="M 84 30 Q 65 54 46 78" stroke="white" strokeOpacity="0.15" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M 60 16 Q 38 50 16 84" stroke="white" strokeOpacity="0.18" strokeWidth="3.5" fill="none" strokeLinecap="round" />
        <path d="M 28 16 Q 50 50 72 84" stroke="black" strokeOpacity="0.07" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M 16 30 Q 35 54 54 78" stroke="black" strokeOpacity="0.05" strokeWidth="3" fill="none" strokeLinecap="round" />
        <path d="M 16 42 Q 50 33 84 42" stroke="white" strokeOpacity="0.18" strokeWidth="1.5" fill="none" strokeLinecap="round" />
        <path d="M 15 55 Q 50 46 85 55" stroke="white" strokeOpacity="0.18" strokeWidth="1.5" fill="none" strokeLinecap="round" />
        <path d="M 18 68 Q 50 59 82 68" stroke="white" strokeOpacity="0.12" strokeWidth="1.5" fill="none" strokeLinecap="round" />
        <ellipse cx="52" cy="73" rx="30" ry="16" fill="black" fillOpacity="0.13" />
        <ellipse cx="37" cy="35" rx="15" ry="11" fill="white" fillOpacity="0.2" />
      </g>

      {/* Needle tips on top of ball */}
      <circle cx="75" cy="92" r="3" fill="#C4A882" />
      <circle cx="92" cy="70" r="3" fill="#C4A882" />
    </svg>
  );
}

// ─── StepItem ────────────────────────────────────────────────────────────────

// Counter rule: only show a sub-row counter when the step describes REPEATED ROWS,
// never for stitch-level repetition within a single row.
//
// "repeat"/"重复" alone are intentionally excluded because they fire on stitch-level
// phrases like "(k1, p1) repeat 12 times" / "重复12次".  Every genuine row-repetition
// case already carries an explicit row count or range that is caught below:
//   • English "rows X-Y"  →  \brows?\s+\d+[-–]\d+\b
//   • Chinese "X-Y行"     →  \d+[-–]\d+\s*行
//   • English "N rows"    →  \d+\s+rows?\b
//   • Chinese "N行"       →  (?<!第)\d{2,}\s*行  (lookbehind skips row labels 第N行)
const REPEAT_RE = /\brows?\s+\d+[-–]\d+\b|\d+[-–]\d+\s*行|(?<!第)\d{2,}\s*行|\d+\s+rows?\b/i;

function isRepeatableStep(step: Step): boolean {
  return (!!step.count && step.count > 1) || REPEAT_RE.test(step.text);
}

function parseMaxCount(step: Step): number | null {
  if (step.count && step.count > 1) return step.count;
  const t = step.text;

  // Chinese "X-Y行" range → Y - X + 1
  // BUT if preceded by an approximation word (约/大约) return null → uncapped counter
  let m = t.match(/(\d+)[-–](\d+)\s*行/);
  if (m) {
    const isApprox = /(?:约|大约|approximately|around|~)\s*\d+[-–]/.test(t);
    return isApprox ? null : parseInt(m[2], 10) - parseInt(m[1], 10) + 1;
  }

  // English "rows X-Y" range → Y - X + 1
  m = t.match(/\brows?\s+(\d+)[-–](\d+)\b/i);
  if (m) return parseInt(m[2], 10) - parseInt(m[1], 10) + 1;

  // "N rows" in English (e.g. "For the next 10 rows")
  // Note: "N times" is intentionally removed — it refers to stitch-level repetition
  m = t.match(/\b(\d+)\s+rows?\b/i);
  if (m) return parseInt(m[1], 10);

  // Chinese "N行" (e.g. "接下来的20行") — exclude row labels like "第N行"
  const allRowNums = [...t.matchAll(/(?<!第)(\d+)\s*行/g)];
  if (allRowNums.length > 0) return parseInt(allRowNums[allRowNums.length - 1][1], 10);

  return null;
}

function StepItem({
  step,
  index,
  onToggle,
  onSubCountChange,
  onTextEdit,
  isEditMode = false,
  onDelete,
}: {
  step: Step;
  index: number;
  onToggle: () => void;
  onSubCountChange: (delta: number) => void;
  onTextEdit: (newText: string) => void;
  isEditMode?: boolean;
  onDelete?: () => void;
}) {
  const [editing, setEditing]   = useState(false);
  const [editText, setEditText] = useState(step.text);
  const inputRef                = useRef<HTMLInputElement>(null);

  const repeatable = isRepeatableStep(step);
  const max        = repeatable ? parseMaxCount(step) : null;
  const subCurrent = step.subCount ?? 0;
  const atMax      = max !== null && subCurrent >= max;

  // Keep draft in sync when step is updated externally (e.g. new conversion)
  useEffect(() => {
    if (!editing) setEditText(step.text);
  }, [step.text, editing]);

  function startEdit(e: React.MouseEvent) {
    if (step.checked) return;
    e.stopPropagation();
    setEditText(step.text);
    setEditing(true);
    requestAnimationFrame(() => inputRef.current?.focus());
  }

  function commitEdit() {
    const trimmed = editText.trim();
    if (trimmed && trimmed !== step.text) onTextEdit(trimmed);
    setEditing(false);
  }

  // Header rows: no checkbox, distinct background, non-interactive
  if (step.isHeader) {
    return (
      <motion.li
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3, delay: index * 0.06 }}
        className="flex items-center gap-2 px-5 py-3 select-none"
        style={{
          background:   "var(--morandi-sage)",
          borderRadius: "1.25rem",
          boxShadow:    "0 2px 10px -4px rgba(163,177,138,0.35)",
        }}
      >
        <span className="text-lg">🧶</span>
        <span className="flex-1 text-sm font-bold leading-snug" style={{ color: "#fff" }}>
          {step.text}
        </span>
        <AnimatePresence>
          {isEditMode && (
            <motion.button
              key="hdr-delete-btn"
              initial={{ opacity: 0, scale: 0.7 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.7 }}
              transition={{ duration: 0.15 }}
              onClick={(e) => { e.stopPropagation(); onDelete?.(); }}
              onPointerDown={(e) => e.stopPropagation()}
              className="no-print shrink-0 flex items-center justify-center w-7 h-7 rounded-full"
              style={{
                background: "rgba(255,255,255,0.18)",
                border:     "1px solid rgba(255,255,255,0.45)",
                color:      "#fff",
                cursor:     "pointer",
              }}
              aria-label="Delete step"
            >
              <Trash2 size={13} strokeWidth={2} />
            </motion.button>
          )}
        </AnimatePresence>
      </motion.li>
    );
  }

  return (
    <motion.li
      initial={{ opacity: 0, x: -20 }}
      animate={{ opacity: step.checked ? 0.65 : 1, x: 0 }}
      transition={{
        opacity: { duration: 0.25, delay: index * 0.06 },
        x: { type: "spring", stiffness: 340, damping: 26, delay: index * 0.06 },
      }}
      whileHover={(editing || isEditMode) ? undefined : { y: -1 }}
      whileTap={(editing || isEditMode) ? undefined : { scale: 0.985 }}
      onClick={(editing || isEditMode) ? undefined : onToggle}
      className={`print-step flex items-start gap-3 px-5 py-4 select-none ${isEditMode ? "cursor-default" : "cursor-pointer"}`}
      data-checked={step.checked}
      style={{
        background:   editing
          ? "rgba(239,246,255,0.7)"
          : step.checked ? "var(--bg)" : "var(--bg-card)",
        border: editing
          ? "1.5px solid #bfdbfe"
          : `1.5px solid ${step.checked ? "var(--border)" : "var(--morandi-stone)"}`,
        borderRadius: "1.25rem",
        boxShadow:    editing || step.checked ? "none" : "0 3px 12px -6px rgba(0,0,0,0.08)",
        transition:   "background 0.2s, border-color 0.2s, box-shadow 0.2s",
      }}
    >
      {/* Checkbox icon */}
      <motion.span
        animate={step.checked ? { scale: [1, 1.3, 1] } : { scale: 1 }}
        transition={{ duration: 0.28 }}
        className="shrink-0 mt-[3px]"
        onClick={(e) => { if (editing) e.stopPropagation(); }}
      >
        {step.checked ? (
          <CheckCircle2 size={22} strokeWidth={1.8} style={{ color: "var(--morandi-green)" }} />
        ) : (
          <Circle size={22} strokeWidth={1.8} style={{ color: "var(--morandi-stone)" }} />
        )}
      </motion.span>

      {/* Text + counter wrapper: row on wide screens, column on mobile */}
      <div className="flex-1 min-w-0 flex flex-col sm:flex-row sm:items-center gap-2">
        <div className="flex-1 min-w-0">

          {/* ── Edit input / display text ── */}
          {editing ? (
            <input
              ref={inputRef}
              value={editText}
              onChange={(e) => setEditText(e.target.value)}
              onBlur={commitEdit}
              onClick={(e) => e.stopPropagation()}
              onPointerDown={(e) => e.stopPropagation()}
              onKeyDown={(e) => {
                if (e.key === "Enter")  { e.preventDefault(); commitEdit(); }
                if (e.key === "Escape") { setEditing(false); }
              }}
              className="w-full text-base font-medium"
              style={{
                background:   "transparent",
                border:       "1px solid #bfdbfe",
                borderRadius: "0.5rem",
                padding:      "1px 6px",
                outline:      "none",
                color:        "var(--text-main)",
                fontFamily:   "var(--font-body)",
                fontSize:     "1rem",
                lineHeight:   "1.625",
              }}
            />
          ) : (
            <span
              className="print-step-text text-base font-medium leading-relaxed"
              onClick={startEdit}
              style={{
                color:          step.checked ? "var(--text-muted)" : "var(--text-main)",
                textDecoration: step.checked ? "line-through" : "none",
                cursor:         step.checked ? "pointer" : "text",
                transition:     "color 0.2s",
                display:        "block",
              }}
            >
              {step.text}
            </span>
          )}

          {/* Original text (translation) */}
          {!editing && step.original && (
            <p
              className="print-step-text-muted mt-0.5 text-xs leading-snug"
              style={{
                color:          "var(--text-muted)",
                opacity:        step.checked ? 0.5 : 0.7,
                textDecoration: step.checked ? "line-through" : "none",
                transition:     "color 0.2s, opacity 0.2s",
              }}
            >
              {step.original}
            </p>
          )}

          {/* Count badge */}
          {!editing && step.count && step.count > 1 && (
            <span
              className="mt-1.5 inline-flex items-center gap-1 text-xs font-semibold px-2 py-0.5 rounded-full"
              style={{
                background: "var(--morandi-pink)",
                color:      "#fff",
                opacity:    step.checked ? 0.5 : 0.9,
              }}
            >
              ×{step.count} rows
            </span>
          )}
        </div>

        {/* Sub-row counter — below text on mobile, right side on wider screens */}
        {repeatable && (
          <div
            className="no-print shrink-0 self-start sm:self-auto flex items-center gap-1.5 rounded-2xl px-2.5 py-1"
            style={{
              background: atMax ? "var(--morandi-green)" : "var(--bg-card)",
              border:     `2px solid ${atMax ? "var(--morandi-green)" : "var(--morandi-stone)"}`,
              boxShadow:  "0 2px 8px -3px rgba(0,0,0,0.10)",
              transition: "background 0.3s, border-color 0.3s",
            }}
            onClick={(e) => e.stopPropagation()}
            onPointerDown={(e) => e.stopPropagation()}
          >
            <button
              onClick={(e) => { e.stopPropagation(); onSubCountChange(-1); }}
              disabled={subCurrent <= 0}
              className="w-6 h-6 flex items-center justify-center rounded-full text-sm font-bold"
              style={{
                color:      subCurrent <= 0 ? "var(--border)" : "var(--text-muted)",
                background: subCurrent <= 0 ? "transparent" : "var(--bg)",
                border:     "none",
                cursor:     subCurrent <= 0 ? "default" : "pointer",
                boxShadow:  subCurrent <= 0 ? "none" : "0 1px 4px -1px rgba(0,0,0,0.12)",
                padding:    0,
                lineHeight: 0,
              }}
            >
              −
            </button>
            <span
              className="text-sm font-bold min-w-[3rem] text-center tabular-nums"
              style={{ color: atMax ? "#fff" : "var(--text-main)" }}
            >
              {subCurrent}{max !== null ? `/${max}` : ""}
            </span>
            <button
              onClick={(e) => { e.stopPropagation(); onSubCountChange(+1); }}
              disabled={atMax}
              className="w-6 h-6 flex items-center justify-center rounded-full text-sm font-bold"
              style={{
                color:      atMax ? "rgba(255,255,255,0.45)" : "#fff",
                background: "var(--morandi-pink)",
                border:     "none",
                cursor:     atMax ? "default" : "pointer",
                boxShadow:  atMax ? "none" : "0 1px 4px -1px rgba(0,0,0,0.18)",
                padding:    0,
                lineHeight: 0,
              }}
            >
              +
            </button>
          </div>
        )}
      </div>

      {/* Delete button — visible only in edit mode */}
      <AnimatePresence>
        {isEditMode && (
          <motion.button
            key="delete-btn"
            initial={{ opacity: 0, scale: 0.7 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.7 }}
            transition={{ duration: 0.15 }}
            onClick={(e) => { e.stopPropagation(); onDelete?.(); }}
            onPointerDown={(e) => e.stopPropagation()}
            className="no-print shrink-0 self-center flex items-center justify-center w-7 h-7 rounded-full"
            style={{
              background: "transparent",
              border:     "1px solid var(--morandi-blush)",
              color:      "var(--morandi-blush)",
              cursor:     "pointer",
            }}
            aria-label="Delete step"
          >
            <Trash2 size={13} strokeWidth={2} />
          </motion.button>
        )}
      </AnimatePresence>
    </motion.li>
  );
}

// ─── StepInsertDividerLi ─────────────────────────────────────────────────────

function StepInsertDividerLi({ onAdd }: { onAdd: () => void }) {
  return (
    <motion.li
      initial={{ opacity: 0, scaleY: 0 }}
      animate={{ opacity: 1, scaleY: 1 }}
      exit={{ opacity: 0, scaleY: 0 }}
      transition={{ duration: 0.18 }}
      className="no-print list-none flex items-center gap-2 cursor-pointer"
      style={{ transformOrigin: "center", padding: "2px 4px" }}
      onClick={onAdd}
    >
      <div className="flex-1 h-px" style={{ background: "var(--border)" }} />
      <motion.span
        whileHover={{ scale: 1.2 }}
        className="flex items-center justify-center w-5 h-5 rounded-full"
        style={{
          background:  "var(--bg-card)",
          border:      "1.5px dashed var(--morandi-sage)",
          color:       "var(--morandi-sage)",
          flexShrink:  0,
        }}
      >
        <Plus size={10} strokeWidth={2.5} />
      </motion.span>
      <div className="flex-1 h-px" style={{ background: "var(--border)" }} />
    </motion.li>
  );
}

// ─── ProjectsModal ────────────────────────────────────────────────────────────

function ProjectsModal({
  projects,
  lang,
  currentProjectId,
  onClose,
  onLoad,
  onDelete,
  onRename,
}: {
  projects: Project[];
  lang: Lang;
  currentProjectId: string | null;
  onClose: () => void;
  onLoad: (id: string) => void;
  onDelete: (id: string) => void;
  onRename: (id: string, name: string) => void;
}) {
  const t = dict[lang];
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editingName, setEditingName] = useState("");
  const nameInputRef = useRef<HTMLInputElement>(null);

  function startRename(id: string, currentName: string) {
    setEditingId(id);
    setEditingName(currentName);
    setTimeout(() => nameInputRef.current?.select(), 0);
  }

  function commitRename() {
    if (editingId && editingName.trim()) {
      onRename(editingId, editingName.trim());
    }
    setEditingId(null);
  }

  return (
    <motion.div
      key="projects-backdrop"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.2 }}
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "rgba(0,0,0,0.32)", backdropFilter: "blur(4px)" }}
      onClick={onClose}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.94, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.94, y: 20 }}
        transition={{ type: "spring", stiffness: 360, damping: 28 }}
        className="w-full max-w-sm flex flex-col gap-4"
        style={{
          background:   "var(--bg-card)",
          border:       "1.5px solid var(--border)",
          boxShadow:    "0 20px 60px -15px rgba(0,0,0,0.25)",
          borderRadius: "2rem",
          padding:      "1.5rem",
          maxHeight:    "75vh",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between">
          <h2 className="flex items-center gap-2 text-base font-bold" style={{ color: "var(--text-main)" }}>
            <Folder size={16} strokeWidth={2} style={{ color: "var(--morandi-green)", flexShrink: 0 }} />
            {t.myProjects}
          </h2>
          <button
            onClick={onClose}
            style={{ background: "none", border: "none", cursor: "pointer", color: "var(--text-muted)", lineHeight: 0, padding: "2px" }}
            aria-label="Close"
          >
            <X size={18} strokeWidth={2} />
          </button>
        </div>

        {/* Project list */}
        <div className="flex flex-col gap-2 overflow-y-auto" style={{ flex: 1 }}>
          {projects.length === 0 ? (
            <p
              className="text-center text-sm py-10"
              style={{ color: "var(--text-muted)" }}
            >
              🧶 {t.noProjects}
            </p>
          ) : (
            projects.map((project) => {
              const isActive   = project.id === currentProjectId;
              const checkable  = project.steps.filter((s) => !s.isHeader);
              const done       = checkable.filter((s) => s.checked).length;
              const total      = checkable.length;
              const date       = new Date(project.lastUpdated).toLocaleDateString(
                lang === "zh" ? "zh-CN" : "en-US",
                { month: "short", day: "numeric" }
              );
              return (
                <div
                  key={project.id}
                  className="flex items-center gap-2 px-4 py-3 rounded-2xl"
                  style={{
                    background: isActive ? "var(--morandi-stone)" : "var(--bg)",
                    border:     `1.5px solid ${isActive ? "var(--morandi-pink)" : "var(--border)"}`,
                    transition: "border-color 0.2s",
                  }}
                >
                  <div className="flex-1 min-w-0">
                    {editingId === project.id ? (
                      <input
                        ref={nameInputRef}
                        value={editingName}
                        onChange={(e) => setEditingName(e.target.value)}
                        onBlur={commitRename}
                        onKeyDown={(e) => {
                          if (e.key === "Enter")  { e.preventDefault(); commitRename(); }
                          if (e.key === "Escape") { setEditingId(null); }
                        }}
                        className="w-full text-sm font-semibold"
                        style={{
                          background:   "transparent",
                          border:       "1px solid var(--morandi-pink)",
                          borderRadius: "0.4rem",
                          padding:      "1px 5px",
                          outline:      "none",
                          color:        "var(--text-main)",
                        }}
                      />
                    ) : (
                      <button
                        onClick={() => startRename(project.id, project.name)}
                        className="flex items-center gap-1 max-w-full text-left"
                        style={{ background: "none", border: "none", cursor: "text", padding: 0 }}
                        title={lang === "zh" ? "点击编辑名称" : "Click to rename"}
                      >
                        <span className="text-sm font-semibold truncate" style={{ color: "var(--text-main)" }}>
                          {project.name}
                        </span>
                        <Edit3 size={11} strokeWidth={2} style={{ color: "var(--text-muted)", flexShrink: 0 }} />
                      </button>
                    )}
                    <p className="text-xs" style={{ color: "var(--text-muted)" }}>
                      {date} · {done}/{total}
                    </p>
                  </div>
                  <button
                    onClick={() => onLoad(project.id)}
                    className="shrink-0 text-xs font-semibold px-3 py-1.5 rounded-full"
                    style={{
                      background: isActive ? "var(--morandi-pink)" : "var(--morandi-green)",
                      color:      "#fff",
                      border:     "none",
                      cursor:     "pointer",
                    }}
                  >
                    {isActive
                      ? (lang === "zh" ? "当前" : "Active")
                      : (lang === "zh" ? "加载" : "Load")}
                  </button>
                  <button
                    onClick={() => onDelete(project.id)}
                    className="shrink-0 flex items-center justify-center w-7 h-7 rounded-full"
                    style={{
                      background: "transparent",
                      color:      "var(--text-muted)",
                      border:     "1px solid var(--border)",
                      cursor:     "pointer",
                    }}
                    aria-label="Delete project"
                  >
                    <X size={12} strokeWidth={2.5} />
                  </button>
                </div>
              );
            })
          )}
        </div>
      </motion.div>
    </motion.div>
  );
}

// ─── LoadingSkeleton ──────────────────────────────────────────────────────────

function LoadingSkeleton() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 10 }}
      transition={{ duration: 0.3 }}
      className="no-print w-full max-w-xl p-8"
      style={{
        background:   "var(--bg-card)",
        border:       "1.5px solid var(--border)",
        boxShadow:    "0 10px 40px -15px rgba(0,0,0,0.05)",
        borderRadius: "2rem",
      }}
    >
      <div className="flex flex-col items-center gap-5 py-6">

        {/* Animated progress dots */}
        <div className="flex items-end gap-1.5">
          {[0, 1, 2, 3, 4, 5, 6].map((i) => (
            <motion.span
              key={i}
              animate={{ scaleY: [0.4, 1, 0.4], opacity: [0.35, 1, 0.35] }}
              transition={{
                repeat:   Infinity,
                duration: 1.1,
                delay:    i * 0.11,
                ease:     "easeInOut",
              }}
              style={{
                display:      "inline-block",
                width:        "6px",
                height:       i % 2 === 0 ? "18px" : "12px",
                borderRadius: "9999px",
                background:   i % 3 === 2
                  ? "var(--morandi-pink)"
                  : "var(--morandi-green)",
                transformOrigin: "bottom",
              }}
            />
          ))}
        </div>

        {/* Skeleton rows */}
        <div className="w-full flex flex-col gap-3 mt-1">
          {[100, 82, 92, 68].map((w, i) => (
            <motion.div
              key={i}
              animate={{ opacity: [0.3, 0.65, 0.3] }}
              transition={{ repeat: Infinity, duration: 1.5, delay: i * 0.18, ease: "easeInOut" }}
              className="h-11 rounded-2xl"
              style={{ width: `${w}%`, background: "var(--border)" }}
            />
          ))}
        </div>
      </div>
    </motion.div>
  );
}
